name: AnalyzeAll

on: [push]

jobs:
  analyzeall:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Git Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: List added files
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
      -
        name: run rayhunter-check
        run: |
          mkdir pages
          for i in *.qmdl; do
            sudo docker run -t -v "${i}:/rayhunter/${i}" rfhs/rayhunter-check:latest "${i}" > "pages/${i/.qmdl}.md"
          done
      -
        name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "pages"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.rayhunterwiki }}
